name: saferide_app_ui_3710154493
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=3.3.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5  # Ensure this is present
  cupertino_icons: ^1.0.6
  saferide_app_ui_3710154493_f2f:
    git: https://f2f.bostonux.com/packages/saferide_app_ui_3710154493_f2f
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  # fonts:
    # - family: Inter
    #   fonts:
    #     - asset: assets/fonts/Inter-Regular.ttf
    #       weight: 400
    #     - asset: assets/fonts/Inter-Medium.ttf
    #       weight: 500
    #     - asset: assets/fonts/Inter-SemiBold.ttf
    #       weight: 600

  assets:
    - assets/icons/homepage_image.png  